# vim:fileencoding=utf-8:ft=conf
# view.conf

# --------------------------------------------------------------------------------
# System
# --------------------------------------------------------------------------------

set -g renumber-windows on
set -g automatic-rename on

# set -g pane-active-border-style fg=colour10

# Pane title
#   Enable:    tmux set -p pane-border-status top
#   Set title: tmux select-pane -T "my-title"
#   Auto-hide when single pane:
#     set-hook -g after-split-window 'if "[ #{window_panes} -gt 1 ]" "set -w pane-border-status top"'
#     set-hook -g pane-exited       'if "[ #{window_panes} -le 2 ]" "set -w pane-border-status off"'
#     (also needs hooks for after-join-pane, after-break-pane, etc.)
# set -g pane-border-status top
set -g pane-border-format " #{?pane_active,#[bg=#7ceabb#,fg=black#,bold],#[bg=#c8f0dc#,fg=#2a4a3a]}#{pane_index}: #{?pane_title,#{pane_title},#{pane_current_command}}#[default] "
set -g pane-border-style fg=colour240
set -g pane-active-border-style fg=colour244

# --------------------------------------------------------------------------------
# Windows
# --------------------------------------------------------------------------------

# TODO: set one-based index for easier jump shortcut navigation
# set -g window-index 1

# https://github.com/koekeishiya/dotfiles
setw -g window-status-format "#[fg=#888888,bg=default,reverse]▓▒░ #I:#W ░▒▓"
setw -g window-status-current-format "#{?window_zoomed_flag,#[fg=#ccaa00#,italics#,reverse],#[bg=default#,fg=#469c76#,reverse]}▓▒░ #I:#W ░▒▓"

# --------------------------------------------------------------------------------
# Status bar
# --------------------------------------------------------------------------------

set-option -g status-position bottom
set -g status-interval 2

# set -g status-fg white
# set -g status-bg black

set -g status-justify 'centre' # NOT center
set -g status-left ''

# set -g status-right '' # '%H:%M'
setw -g status-left ""
setw -g status-right "#{?#{==:#{client_key_table},modal},#[bg=default#,fg=#ccaa00#,reverse],#[bg=default#,fg=#469c76#,reverse]}▓▒░ #S ░▒▓"

# --------------------------------------------------------------------------------
# Transparent status bar
# --------------------------------------------------------------------------------

set -g status-style bg=default
set -g status-left-style bg=default
set -g status-right-style bg=default

