#!/usr/bin/env sh

# yabai -m config manage                on

# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

# TODO: use mouse

# behaviors
yabai -m config split_ratio                  0.50
yabai -m config layout                       bsp
# yabai -m config layout                       float
yabai -m config auto_balance                 on

# control
yabai -m config mouse_modifier               fn  # FIXME
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# view
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_border                off
# yabai -m config window_border                on
yabai -m config window_border_width          4

# color
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f

# padding/gap policy
yabai -m config top_padding                  0 # 20
yabai -m config bottom_padding               0 # 20
yabai -m config left_padding                 0 # 20
yabai -m config right_padding                0 # 20
yabai -m config window_gap                   0 # 10

# opacity
yabai -m config window_opacity               off
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.8



# use spacebar to show status bar
# (spaecbar: https://github.com/somdoron/spacebar)
# yabai -m config top_padding                  26

# use simple-bar
# yabai -m config top_padding                  28
yabai -m config top_padding                  0

echo "yabai configuration loaded.."

