# [emacs-straight]
# src.git = "https://github.com/radian-software/straight.el"
# src.branch = "master"
# fetch.github = "radian-software/straight.el"

# [emacs-smyx]
# src.git = "https://github.com/tacit7/smyx"
# src.branch = "master"
# fetch.github = "tacit7/smyx"

[emacs-smyx]
src.git = "https://github.com/toyboot4e/smyx"
src.branch = "master"
fetch.github = "toyboot4e/smyx"

