# Just a task runner
# <https://github.com/casey/just>

# shows this help message
help:
    @just -l

# formats the nix files
format:
    nix fmt .

# updates channels and flakes
update:
    sudo nix-channel --update
    nix flake update

# updates specific flake input
update-input name:
    nix flake lock --update-input {{name}}

fetch:
    nix run github:berberman/nvfetcher

# updates the whole NixOS system
nixos:
    sudo nixos-rebuild --flake .#tbm switch

# updates the whole macOS system
macos:
    sudo nix run nix-darwin --extra-experimental-features 'flakes nix-command' -- switch --flake .#mac switch

