# Just a task runner
# <https://github.com/casey/just>

# shows this help message
help:
    @just -l

# updates the whole system
nixos:
    # sudo nix-channel --update
    # nix flake update
    sudo nixos-rebuild --flake .#tbm switch

# updates the macOS's whole system
macos:
    # sudo nix-channel --update
    # nix flake update
    sudo nix run nix-darwin --extra-experimental-features 'flakes nix-command' -- switch --flake .#mac switch

# updates specific flake input
update-input name:
    nix flake lock --update-input {{name}}

