# [emacs-straight]
# src.git = "https://github.com/radian-software/straight.el"
# src.branch = "master"
# fetch.github = "radian-software/straight.el"

[emacs-smyx]
src.git = "https://github.com/tacit7/smyx"
src.branch = "master"
fetch.github = "tacit7/smyx"

[plover-harri-numbers]
src.git = "https://github.com/StenoHarri/Harri_numbers"
src.branch = "main"
fetch.github = "StenoHarri/Harri_numbers"

