# [emacs-straight]
# src.git = "https://github.com/radian-software/straight.el"
# src.branch = "master"
# fetch.github = "radian-software/straight.el"

[emacs-smyx]
src.git = "https://github.com/tacit7/smyx"
src.branch = "master"
fetch.github = "tacit7/smyx"

[plover-harri-numbers]
src.git = "https://github.com/StenoHarri/Harri_numbers"
src.branch = "main"
fetch.github = "StenoHarri/Harri_numbers"

[fish-bd]
src.git = "https://github.com/0rax/fish-bd"
src.branch = "master"
fetch.github = "0rax/fish-bd"

[fish-nix-completions]
src.git = "https://github.com/kidonng/nix-completions.fish"
src.branch = "master"
fetch.github = "kidonng/nix-completions.fish"

[fish-nix-env]
src.git = "https://github.com/lilyball/nix-env.fish"
src.branch = "master"
fetch.github = "lilyball/nix-env.fish"

[fish-z]
src.git = "https://github.com/jethrokuan/z"
src.branch = "master"
fetch.github = "jethrokuan/z"

