# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  emacs-smyx = {
    pname = "emacs-smyx";
    version = "ce6dc4b1c25ff8c1d6c9b9015e0199355c46be4d";
    src = fetchFromGitHub {
      owner = "tacit7";
      repo = "smyx";
      rev = "ce6dc4b1c25ff8c1d6c9b9015e0199355c46be4d";
      fetchSubmodules = false;
      sha256 = "sha256-1UZRtQ74p4xAuB6JXFHMxrNBO9BG6JPRYLvEeCOz5rc=";
    };
    date = "2024-09-14";
  };
  plover-harri-numbers = {
    pname = "plover-harri-numbers";
    version = "5a890fc2877dba3fd2a0e690ceed7492dcc93388";
    src = fetchFromGitHub {
      owner = "StenoHarri";
      repo = "Harri_numbers";
      rev = "5a890fc2877dba3fd2a0e690ceed7492dcc93388";
      fetchSubmodules = false;
      sha256 = "sha256-N82WGmgdWtrFsFT9KB/lsPlym/L1ztLYdynBpj7h4F8=";
    };
    date = "2025-06-09";
  };
}
