# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  plover-harri-numbers = {
    pname = "plover-harri-numbers";
    version = "5a890fc2877dba3fd2a0e690ceed7492dcc93388";
    src = fetchFromGitHub {
      owner = "StenoHarri";
      repo = "Harri_numbers";
      rev = "5a890fc2877dba3fd2a0e690ceed7492dcc93388";
      fetchSubmodules = false;
      sha256 = "sha256-N82WGmgdWtrFsFT9KB/lsPlym/L1ztLYdynBpj7h4F8=";
    };
    date = "2025-06-09";
  };
}
