# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  emacs-smyx = {
    pname = "emacs-smyx";
    version = "97a2e1ef2bcffd34e43b1cabad17d317e41258ec";
    src = fetchFromGitHub {
      owner = "toyboot4e";
      repo = "smyx";
      rev = "97a2e1ef2bcffd34e43b1cabad17d317e41258ec";
      fetchSubmodules = false;
      sha256 = "sha256-1UZRtQ74p4xAuB6JXFHMxrNBO9BG6JPRYLvEeCOz5rc=";
    };
    date = "2024-09-14";
  };
}
